### ISSUE TITLE
Python-histogram fails on TIV variable

### ISSUE THREAD

**Issue by ludovicc** [LREN-CHUV/algorithm-repository#10]
Seen using latest web-analytics-starter:

```
0bdc026ca55c        hbpmip/python-histograms:0.3.6        "python /histograms.…"   55 seconds ago       Exited (1) 53 seconds ago                                               

docker logs 0bdc026ca55c                                         2 changed files  master 
INFO:root:Using default number of bins: 20
Traceback (most recent call last):
  File "/histograms.py", line 149, in <module>
    main()
  File "/histograms.py", line 37, in main
    histograms_results = compute_histograms(dep_var, indep_vars, nb_bins)
  File "/histograms.py", line 46, in compute_histograms
    histograms.append(compute_histogram(dep_var, nb_bins=nb_bins))
  File "/histograms.py", line 59, in compute_histogram
    categories, categories_labels = compute_categories(dep_var, nb_bins)
  File "/histograms.py", line 91, in compute_categories
    minimum = min(values)
ValueError: min() arg is an empty sequence

"PARAM_covariables=",
"PARAM_grouping=dataset,gender,agegroup,alzheimerbroadcategory",
"PARAM_meta={\"tiv\":{\"description\":\"Total intra-cranial volume\",\"methodology\":\"lren-nmm-volumes\",\"label\":\"TIV\",\"code\":\"tiv\",\"units\":\"cm3\",\"type\":\"real\"},\"agegroup\":{\"enumerations\":[{\"code\":\"-50y\",\"label\":\"-50y\"},{\"code\":\"50-59y\",\"label\":\"50-59y\"},{\"code\":\"60-69y\",\"label\":\"60-69y\"},{\"code\":\"70-79y\",\"label\":\"70-79y\"},{\"code\":\"+80y\",\"label\":\"+80y\"}],\"description\":\"Age Group\",\"methodology\":\"mip-cde\",\"label\":\"Age Group\",\"code\":\"agegroup\",\"type\":\"polynominal\"},\"alzheimerbroadcategory\":{\"enumerations\":[{\"code\":\"AD\",\"label\":\"Alzheimer's disease\"},{\"code\":\"CN\",\"label\":\"Cognitively Normal\"},{\"code\":\"Other\",\"label\":\"Other\"}],\"description\":\"There will be two broad categories taken into account. Alzheimer's disease (AD) in which the diagnostic is 100% certain and \\\"Other\\\" comprising the rest of Alzheimer's related categories. The \\\"Other\\\" category refers to Alzheime's related diagnosis which origin can be traced to other pathology eg. vascular. In this category MCI diagnosis can also be found. In summary, all Alzheimer's related diagnosis that are not pure.\",\"methodology\":\"mip-cde\",\"label\":\"Alzheimer Broad Category\",\"code\":\"alzheimerbroadcategory\",\"type\":\"polynominal\"},\"dataset\":{\"enumerations\":[{\"code\":\"cde_features_a\",\"label\":\"CHUV\"},{\"code\":\"cde_features_b\",\"label\":\"Brescia\"},{\"code\":\"cde_features_c\",\"label\":\"Lille\"}],\"description\":\"Variable used to differentiate datasets.\",\"methodology\":\"mip-cde\",\"label\":\"Dataset\",\"code\":\"dataset\",\"type\":\"polynominal\"},\"gender\":{\"enumerations\":[{\"code\":\"M\",\"label\":\"Male\"},{\"code\":\"F\",\"label\":\"Female\"}],\"description\":\"Gender of the patient - Sex assigned at birth\",\"methodology\":\"mip-cde\",\"label\":\"Gender\",\"code\":\"gender\",\"length\":1,\"type\":\"binominal\"}}",
"PARAM_query=SELECT \"tiv\",\"dataset\",\"gender\",\"agegroup\",\"alzheimerbroadcategory\" FROM cde_features_a WHERE \"tiv\" IS NOT NULL",
"PARAM_variables=tiv"

```

**Comment by Marigold** [comment]
Fails because all TIV values are null. It is solved in https://github.com/LREN-CHUV/algorithm-repository/pull/11 by raising an error.

**Comment by ludovicc** [comment]
Fixed
