### ISSUE TITLE
Tests for python-knn are failing

### ISSUE THREAD

**Issue by ludovicc** [LREN-CHUV/algorithm-repository#21]
While running python-knn/tests/test.sh:

```
Run the distributed-knn...
WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
Starting tests_db_1 ... done
Traceback (most recent call last):
  File "/knn.py", line 28, in <module>
    from sklearn_to_pfa.sklearn_to_pfa import sklearn_to_pfa
  File "/usr/local/lib/python3.6/site-packages/sklearn_to_pfa/sklearn_to_pfa.py", line 23, in <module>
    import titus.prettypfa
  File "/usr/local/lib/python3.6/site-packages/titus/prettypfa.py", line 26, in <module>
    from titus.pfaast import Subs
  File "/usr/local/lib/python3.6/site-packages/titus/pfaast.py", line 25, in <module>
    import titus.lib.core
  File "/usr/local/lib/python3.6/site-packages/titus/lib/core.py", line 25, in <module>
    from titus.signature import Sig
  File "/usr/local/lib/python3.6/site-packages/titus/signature.py", line 23, in <module>
    import titus.P as P
  File "/usr/local/lib/python3.6/site-packages/titus/P.py", line 20, in <module>
    from titus.datatype import Type
  File "/usr/local/lib/python3.6/site-packages/titus/datatype.py", line 23, in <module>
    import avro.io
  File "/usr/local/lib/python3.6/site-packages/avro/io.py", line 200
    bits = (((ord(self.read(1)) & 0xffL)) |
                                      ^
```

**Comment by ludovicc** [comment]
@Marigold Now I have this:

Run the distributed-knn...
WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
Starting tests_db_1 ... done
INFO:root:Creating new estimator
Traceback (most recent call last):
  File "/knn.py", line 123, in <module>
    compute()
  File "/knn.py", line 70, in compute
    pfa = sklearn_to_pfa(estimator, types, featurizer.generate_pretty_pfa())
  File "/usr/local/lib/python3.6/site-packages/sklearn_to_pfa-0.1.2-py3.6.egg/sklearn_to_pfa/sklearn_to_pfa.py", line 53, in sklearn_to_pfa
    raise NotImplementedError('Estimator {} is not yet supported'.format(estimator.__class__.__name__))
NotImplementedError: Estimator KNeighborsRegressor is not yet supported

**Comment by Marigold** [comment]
I somehow forgot to push a few commits, they are in this PR https://github.com/LREN-CHUV/python-base-docker-images/pull/5. I haven't been able to test it thoroughly though, I'm at a site with a poor internet connection and tests with docker are taking ages :(

**Comment by ludovicc** [comment]
I've found the issue and fixed it. Thanks
